{
    "CreateLinks": [],
    "OnFailure": "/RisksMobile/Actions/CreateEntityFailureMessage.action",
    "OnSuccess": "/RisksMobile/Actions/CreateEntitySuccessMessage.action",
    "Properties": {
        "title": "#Control:title/#Value",
        "prio": "#Control:prio/#Value",
        "descr": "#Control:descr/#Value",
        "impact": "#Control:impact/#Value",
        "criticality": "#Control:criticality/#Value",
        "supplier_BusinessPartner": "#Control:supplier_BusinessPartner/#SelectedValue"
    },
    "Target": {
        "EntitySet": "Risks",
        "Service": "/RisksMobile/Services/service1.service"
    },
    "ActionResult": {
        "_Name": "create"
    },
    "_Type": "Action.Type.ODataService.CreateEntity"
}